from setuptools import setup

setup(
    name='svg-captcha-solver',
    version='0.1.0',
    description='A simple python module to solve svg-captcha generated by npm svg-captcha package.',
    author='dinhit',
    author_email='dinhitcom@gmail.com',
    packages=['svg_captcha_solver']
)